problem:
  n: 100
  perturb: True
  t_max: 6.28
  x0: 1
  y0: 0

training:
  method: 'unsupervised'
  seed: 1
  niters: 20000
  g_lr: 0.005997518415564992
  d_lr: 5.401739244306492e-05
  g_betas: [0.69869083, 0.59402419]
  d_betas: [0.32980614, 0.56526729]
  lr_schedule: True
  gamma: 0.9996422662507756
  obs_every: 1
  d1: 1
  d2: 1
  G_iters: 1
  D_iters: 1
  loss_fn: MSELoss
  wgan: False
  gp: 0.1
  conditional: False
  log: True
  plot: True
  save: True
  save_for_animation: True
  dirname: 'COO_run_gan_besthypers_test'

generator:
  in_dim: 1
  out_dim: 2
  n_hidden_units: 40
  n_hidden_layers: 4
  activation: 'Tanh'
  residual: True
  regress: True

discriminator:
  in_dim: 2
  out_dim: 1
  n_hidden_units: 40
  n_hidden_layers: 2
  activation: 'Tanh'
  residual: True
  regress: False
  spectral_norm: True
