problem:
  n: 100
  perturb: True
  t_max: 10

training:
  method: 'unsupervised'
  seed: 0
  niters: 500
  g_lr: 0.01
  d_lr: 0.01
  g_betas: [0.9, 0.999]
  d_betas: [0.9, 0.999]
  lr_schedule: True
  gamma: 1.0
  obs_every: 1
  d1: 1
  d2: 1
  G_iters: 1
  D_iters: 1
  wgan: False
  gp: 0.1
  conditional: True
  plot: True
  save: False
  fname: 'EXP.png'

generator:
  in_dim: 1
  out_dim: 1
  n_hidden_units: 20
  n_hidden_layers: 2
  activation: 'LeakyReLU'
  residual: True
  regress: True

discriminator:
  in_dim: 2
  out_dim: 1
  n_hidden_units: 20
  n_hidden_layers: 2
  activation: 'LeakyReLU'
  residual: True
  regress: False
  spectral_norm: True
