problem:
  n: 100
  perturb: True
  t_max: 10

training:
  method: 'unsupervised'
  seed: 0
  niters: 2000 # 500
  g_lr: 0.008467333205384038 # 0.01785332956321333
  # classical tuning (with MSE) below:
  # g_lr: 0.009150356729447341
  d_lr: 0.000469485661628429 # 0.0025312451764215923
  g_betas: [0.67103718, 0.14351227] # [0.9, 0.999]
  d_betas: [0.86631674, 0.16513108] # [0.9, 0.999]
  lr_schedule: True # False
  gamma: 0.9907226708922195 # 0.99
  obs_every: 1
  d1: 1
  d2: 1
  G_iters: 1
  D_iters: 1
  loss_fn: L1Loss
  wgan: False
  gp: 0.1
  conditional: False
  log: True
  plot: True
  save: True
  save_for_animation: False
  dirname: 'EXP_run_gan_053020'

generator:
  in_dim: 1
  out_dim: 1
  n_hidden_units: 30 # 20
  n_hidden_layers: 2
  activation: 'Tanh'
  residual: True
  regress: True

discriminator:
  in_dim: 1
  out_dim: 1
  n_hidden_units: 20
  n_hidden_layers: 4 # 2
  activation: 'Tanh'
  residual: True
  regress: False
  spectral_norm: True
