problem:
  n: 400
  perturb: True
  t_max: 12.56
  dx_dt0: 0.5

training:
  method: 'unsupervised'
  seed: 0
  niters: 3000
  g_lr: 0.005801628839417561 # 0.017527633279259706
  d_lr: 0.0007291873762250555 # 2.4036439049494245e-05
  g_betas: [0.10244627, 0.76328835] # [0.9, 0.999]
  d_betas: [0.54142685, 0.67750577] # [0.9, 0.999]
  lr_schedule: True
  gamma: 0.9962712909742575 # 0.999
  obs_every: 1
  d1: 1
  d2: 1
  G_iters: 1
  D_iters: 1
  loss_fn: SmoothL1Loss
  wgan: False
  gp: 0.1
  conditional: False
  log: True
  plot: True
  save: True
  dirname: 'NLO_run_March22_smoothL1'

generator:
  in_dim: 1
  out_dim: 1
  n_hidden_units: 20
  n_hidden_layers: 2
  activation: 'Tanh'
  residual: True
  regress: True

discriminator:
  in_dim: 1
  out_dim: 1
  n_hidden_units: 20
  n_hidden_layers: 2
  activation: 'Tanh'
  residual: True
  regress: False
  spectral_norm: True
