problem:
  n: 400
  perturb: True
  t_max: 12.56
  dx_dt0: 0.5

training:
  method: 'unsupervised'
  seed: 0
  niters: 20000
  g_lr: 0.00580162883941
  d_lr: 0.0007291873762250
  g_betas: [0.10244627, 0.76328835]
  d_betas: [0.54142685, 0.67750577]
  lr_schedule: True
  gamma: 0.999
  obs_every: 1
  d1: 1
  d2: 1
  G_iters: 1
  D_iters: 1
  loss_fn: MSELoss
  wgan: False
  gp: 0.1
  conditional: False
  log: True
  plot: True
  save: True
  save_for_animation: False
  dirname: 'NLO_run'

generator:
  in_dim: 1
  out_dim: 1
  n_hidden_units: 40
  n_hidden_layers: 4
  activation: 'Tanh'
  residual: True
  regress: True

discriminator:
  in_dim: 1
  out_dim: 1
  n_hidden_units: 30
  n_hidden_layers: 3
  activation: 'Tanh'
  residual: True
  regress: False
  spectral_norm: True
