problem:
  nx: 40
  ny: 40
  f: 10
  perturb: True

training:
  method: 'unsupervised'
  seed: 0
  niters: 500
  g_lr: 0.001
  d_lr: 0.001
  g_betas: [0.9, 0.999]
  d_betas: [0.9, 0.999]
  lr_schedule: False
  gamma: 0.99
  obs_every: 1
  d1: 1
  d2: 1
  G_iters: 1
  D_iters: 1
  wgan: False
  gp: 0.1
  conditional: False
  log: True
  plot: True
  save: True
  dirname: 'POS_run'

generator:
  in_dim: 2
  out_dim: 1
  n_hidden_units: 64
  n_hidden_layers: 2
  activation: 'Tanh'
  residual: True
  regress: True

discriminator:
  in_dim: 1
  out_dim: 1
  n_hidden_units: 64
  n_hidden_layers: 2
  activation: 'Tanh'
  residual: True
  regress: False
  spectral_norm: True
