problem:
  n: 200
  perturb: True
  t_max: 10
  S0: 0.7 # 0.99
  I0: 0.3 # 0.01
  R0: 0.0
  beta: 3
  gamma: 1

training:
  method: 'unsupervised'
  seed: 0
  niters: 5000
  g_lr: 0.006429803531841584
  d_lr: 0.009647103812410594
  g_betas: [0.14666949, 0.93261048]
  d_betas: [0.51750004, 0.85405624]
  lr_schedule: True
  gamma: 0.9976839429505154
  obs_every: 1
  d1: 1
  d2: 1
  G_iters: 1
  D_iters: 1
  loss_fn: SmoothL1Loss
  wgan: False
  gp: 0.1
  conditional: False
  log: True
  plot: True
  save: True
  dirname: 'SIR_run_March22_noncollapse_energy_gan'

generator:
  in_dim: 1
  out_dim: 3
  n_hidden_units: 20
  n_hidden_layers: 2
  activation: 'Tanh'
  residual: True
  regress: True

discriminator:
  in_dim: 3
  out_dim: 1
  n_hidden_units: 20
  n_hidden_layers: 2
  activation: 'Tanh'
  residual: True
  regress: False
  spectral_norm: True
