problem:
  n: 800
  perturb: True
  t_max: 10
  S0: 0.99
  I0: 0.01
  R0: 0.0
  beta: 3
  gamma: 1

training:
  method: 'unsupervised'
  seed: 0
  niters: 30000
  g_lr: 0.009949364998471707
  d_lr: 0.002177634209548115
  g_betas: [0.20705222, 0.16897627]
  d_betas: [0.19268249, 0.61740443]
  lr_schedule: True
  gamma: 0.9996
  obs_every: 1
  d1: 1
  d2: 1
  G_iters: 1
  D_iters: 1
  loss_fn: MSELoss
  wgan: False
  gp: 0.1
  conditional: False
  log: True
  plot: True
  save: True
  save_for_animation: False
  dirname: 'SIR_run'

generator:
  in_dim: 1
  out_dim: 3
  n_hidden_units: 40
  n_hidden_layers: 2
  residual: True
  regress: True

discriminator:
  in_dim: 3
  out_dim: 1
  n_hidden_units: 20
  n_hidden_layers: 3
  activation: 'Tanh'
  residual: True
  regress: False
  spectral_norm: True
