name: denn
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - torchvision
  - pytorch
  - tqdm
  - pandas
  - jupyterlab
  - matplotlib
  - scipy
  - fenics
  - pyyaml
  - boto3
  - plotly
  - plotly-orca
